title: John Ashabahebwa
email: me@johnashabahebwa.com
keywords:
  - john
  - ashaba
  - ashabahebwa
  - ash
  - software
description: >- # this means to ignore newlines until "baseurl:"
  This is Ash - the Software Engineer. You have landed on my site, welcome! You don’t have to over stay.
baseurl: ""
url: "https://johnashabahebwa.com"
twitter_username: johnashabahebwa
github_username:  ashaba

plugins:
  - jekyll-feed
  - jekyll-seo-tag
