title: John Ashabahebwa
email: me@johnashabahebwa.com
keywords:
  - john
  - ashaba
  - ashabahebwa
  - ash
  - software
description: >- # this means to ignore newlines until "baseurl:"
  I write software, play piano (still learning!), and on weekends, I’m a full-time dad.
baseurl: ""
url: "https://johnashabahebwa.com"
twitter_username: johnashabahebwa
github_username:  ashaba

plugins:
  - jekyll-feed
  - jekyll-seo-tag
